### ISSUE TITLE
Shield growth feedback loop with Transcendence and shield items

### ISSUE THREAD

**Issue by shawncrobinson** [Keroro1454/Supply-Drop#15]
As a result of the new shield item + transcendence calculation, the player's shield will continue to grow to infinity after achieving >100% of health as shield.

[Example video](https://user-images.githubusercontent.com/42318986/105566924-9873f580-5ce3-11eb-8294-594a7c888678.mp4)
The mods enabled for this video were Supply Drop's dependencies and a cheat menu to spawn in items, but the issue has been observed without the cheat menu.

**Comment by Keroro1454** [comment]
This is an ugly one, I think I've got a fix prepared and will rush a fix ASAP. Thank you for calling it to my attention.

**Comment by Keroro1454** [comment]
Fixed in 1.4.5. It was something to do with using shield in the calculations, I've changed it so that Transcendence + shield items will only draw from player levelMaxHealth for the calculations. This is an imperfect solution because it will ignore any HP gains from Titanic Knurls and Infusions, but these are minor omissions. I'll come back to this at some point to see if I can find a work-around, but this should be good for now.

Thank you for the well-documented report! Your contribution has been noted in the changelog!
