### ISSUE TITLE
Balance Suggestions.

### ISSUE THREAD

**Issue by Coffe-e** [Keroro1454/Supply-Drop#18]
Salvaged Wires: A buff to the atkspeed bonus, since it's conditional, and the initial shield goes away pretty fast. Maybe equal to soldier's on the first stack?

Plague Hat: [1%], or even [0.5%] Max HP instead of [2%]. since it's a bit ridiculous

Electro-Voltaic Plankton: (1% +1 [+1 per stack]) shield instead of just a flat [+1] could help differentiate it from leeching seed more.

Shell Plating: [15 or 20] armor max [+15], since [10] armor isn't a lot for requiring an on-kill effect

**Comment by Keroro1454** [comment]
Working on the mod again!

Salvaged Wires: I'll be keeping them as is since it grants you shield and the attack speed. Even if it is conditional attack speed, the item is also granting you a slight amount of survivability, justifying the lesser AS buff.

Plague Hat: Already implemented.

Plankton: I'll consider this but they're actively supposed to feel like "the shield version of leeching seed". I think the more limited means of recovering shield plays better with having shield granting you valuable bonuses via other items in the mod, compared to health which doesn't have such beneficial synergies but can be recovered more easily (scythe, etc.). If anything, I think Leeching Seed is the one that needs the buff!

Shell Plating: Boosting it up a lot per this rec, highly agree the item felt pretty unimpactful.

Thanks for your suggestions, hope you'll enjoy the mod when it comes out soon!
