### ISSUE TITLE
Shield items & Transcendence

### ISSUE THREAD

**Issue by sanity-dance** [Keroro1454/Supply-Drop#8]
Here is the documentation you requested.

All mods other than Supply Drop and its dependencies have been disabled.

In a previous test, I noted some inconsistencies. After picking up a QSS, subsequent stacks of Wires and Ties increased shields properly. I have not been able to reproduce this behavior.

![shieldbefore](https://user-images.githubusercontent.com/58183513/104369045-c1b9a800-54d1-11eb-8517-f3fe57689d78.png)

![shieldafter](https://user-images.githubusercontent.com/58183513/104369065-c54d2f00-54d1-11eb-84b1-7c90e03c32fe.png)

![shieldafter2](https://user-images.githubusercontent.com/58183513/104369079-c7af8900-54d1-11eb-9c44-412b532b74e8.png)

![shieldafter3](https://user-images.githubusercontent.com/58183513/104369093-caaa7980-54d1-11eb-87db-989beda4224f.png)

![shieldafter4](https://user-images.githubusercontent.com/58183513/104369099-cc743d00-54d1-11eb-88c4-a337a0be3e73.png)

_Originally posted by @sanity-dance in https://github.com/Keroro1454/Supply-Drop/issues/6#issuecomment-758930573_

**Comment by Keroro1454** [comment]
Fixed in 1.4.2. If you have Transcendence, shield items will now calculate their additional % gains based off of HP _and_ shield. 

Technically, it's still not totally functional, in that it isn't how vanilla processes shield items + Transcendence (In vanilla, shield items are simply calculated before the Transcendence calculations to maxHealth are performed), but personally I find vanilla's calculations poorly-devised in this specific situation (as they utilize your pre-Transcendence but post-Infusion/Bitter Root/etc. maxHealth, which only exists at all due to the order of when calculations are done--it is effectively undeterminable in-game), so hopefully it won't be a problem.

Thank you again for the report!
